(TeX-add-style-hook "compterendu"
 (lambda ()
    (TeX-run-style-hooks
     "hyperref"
     "natbib"
     "numbers"
     "super"
     "comma"
     "sort&compress"
     "setspace"
     "pdfcolmk"
     "color"
     "graphicx"
     "array"
     "amsfonts"
     "amssymb"
     "amsmath"
     "lmodern"
     "fontenc"
     "T1"
     "babel"
     "francais"
     "inputenc"
     "utf8"
     "geometry"
     "latex2e"
     "art11"
     "article"
     "a4paper"
     "11pt")))

