#!/usr/bin/env python
# -*- noplot -*-
# from https://github.com/ssalentin/pymol-animations/blob/master/tutorials/basics/*.py #

from pymol import *


# The next line is essential to prevent any threading errors. Call this function before using any PyMOl methods!
pymol.finish_launching()


# Next, we configure some global settings which are needed for our movies.
cmd.set('scene_buttons', 1)  # This installs scene buttons to switch between scenes
cmd.set('matrix_mode', 1)  # This sets up a mode needed for animations.
cmd.set('movie_panel', 1) # This setting shows a slider to interactively move between frames

# Finally, we have to think about the length and quality of our animation
cmd.mset("1 x500")  # How many frames do we need?. 500 frames are enough for a 20 seconds video with 25 frames/second
cmd.set('ray_trace_frames', 1)  # Should the frames be ray-traced? If yes, rendering will take longer, but look nicer.
cmd.viewport(800, 800) # Choose the desired resolution for the movie here (in pixels).

# parametres generaux pour realiser un film
    # le parametre cache_frames permet de m

for idx in range(1,1001):
    cmd.load("LYS-%04d.pdb"%idx,"mov")


    
cmd.load("LYS-00.pdb","00")
cmd.load("LYS-01.pdb","01")
cmd.load("LYS-02.pdb","02")
cmd.load("LYS-03.pdb","03")
cmd.load("LYS-04.pdb","04")
cmd.load("LYS-05.pdb","05")
cmd.load("LYS-06.pdb","06")
cmd.load("LYS-07.pdb","07")
cmd.load("LYS-08.pdb","08")
cmd.load("LYS-09.pdb","09")
cmd.load("LYS-10.pdb","10")
cmd.load("LYS-11.pdb","11")
cmd.load("LYS-12.pdb","12")
cmd.load("LYS-13.pdb","13")
cmd.load("LYS-14.pdb","14")
cmd.load("LYS-15.pdb","15")
cmd.load("LYS-16.pdb","16")
cmd.load("LYS-17.pdb","17")
cmd.load("LYS-18.pdb","18")
cmd.load("LYS-19.pdb","19")
cmd.load("LYS-20.pdb","20")
cmd.load("LYS-21.pdb","21")
cmd.load("LYS-22.pdb","22")
cmd.load("LYS-23.pdb","23")
cmd.load("LYS-24.pdb","24")
cmd.load("LYS-25.pdb","25")
cmd.load("LYS-16.pdb","26")
cmd.load("LYS-27.pdb","27")
cmd.load("LYS-28.pdb","28")
cmd.load("LYS-29.pdb","29")
cmd.load("LYS-30.pdb","30")
cmd.load("LYS-31.pdb","31")
cmd.load("LYS-32.pdb","32")
cmd.load("LYS-33.pdb","33")
cmd.load("LYS-34.pdb","34")
cmd.load("LYS-35.pdb","35")
cmd.load("LYS-36.pdb","36")
cmd.load("LYS-37.pdb","37")
cmd.load("LYS-38.pdb","38")
cmd.load("LYS-39.pdb","39")
cmd.load("LYS-40.pdb","40")
cmd.load("LYS-41.pdb","41")
cmd.load("LYS-42.pdb","42")
cmd.load("LYS-43.pdb","43")
cmd.load("LYS-44.pdb","44")
cmd.load("LYS-45.pdb","45")
cmd.load("LYS-46.pdb","46")
cmd.load("LYS-47.pdb","47")
cmd.load("LYS-48.pdb","48")

cmd.hide('everything','all')

cmd.mset("1 x49")
cmd.frame("1")
cmd.mview("store")
cmd.frame("2")
cmd.show("(00)")
cmd.mview("store")
cmd.hide('(00)')
cmd.frame("3")
cmd.show("(01)")
cmd.mview("store")
cmd.hide('everything','all')
cmd.frame("4")
cmd.show("(02)")
cmd.mview("store")
cmd.hide('everything','all')
cmd.frame("5")
cmd.show("(03)")
cmd.mview("store")
cmd.hide('everything','all')
cmd.frame("6")
cmd.show("(04)")
cmd.mview("store")
cmd.hide('everything','all')
cmd.frame("7")
cmd.show("(05)")
cmd.mview("store")
cmd.hide('everything','all')
cmd.frame("8")
cmd.show("(06)")
cmd.mview("store")
cmd.hide('everything','all')
cmd.frame("9")
cmd.show("(07)")
cmd.mview("store")
cmd.hide('everything','all')
cmd.frame("10")
cmd.show("(08)")
cmd.mview("store")
cmd.hide('everything','all')
cmd.frame("11")
cmd.show("(09)")
cmd.mview("store")
cmd.hide('everything','all')
cmd.frame("12")
cmd.show("(10)")
cmd.mview("store")
cmd.hide('everything','all')
cmd.frame("13")
cmd.show("(11)")
cmd.mview("store")
cmd.hide('everything','all')
cmd.frame("14")
cmd.show("(12)")
cmd.mview("store")
cmd.hide('everything','all')
cmd.frame("15")
cmd.show("(13)")
cmd.mview("store")
cmd.hide('everything','all')
cmd.frame("16")
cmd.show("(14)")
cmd.mview("store")
cmd.hide('everything','all')
cmd.frame("17")
cmd.show("(15)")
cmd.mview("store")
cmd.hide('everything','all')
cmd.frame("2")
cmd.show("(16)")
cmd.mview("store")
cmd.hide('everything','all')
cmd.frame("2")
cmd.show("(17)")
cmd.mview("store")
cmd.hide('everything','all')
cmd.frame("2")
cmd.show("(18)")
cmd.mview("store")
cmd.hide('everything','all')
cmd.frame("2")
cmd.show("(19)")
cmd.mview("store")
cmd.hide('everything','all')
cmd.frame("2")
cmd.show("(20)")
cmd.mview("store")
cmd.hide('everything','all')
cmd.frame("2")
cmd.show("(21)")
cmd.mview("store")
cmd.hide('everything','all')
cmd.frame("2")
cmd.show("(22)")
cmd.mview("store")
cmd.hide('everything','all')
cmd.frame("2")
cmd.show("(23)")
cmd.mview("store")
cmd.hide('everything','all')
cmd.frame("2")
cmd.show("(24)")
cmd.mview("store")
cmd.hide('everything','all')
cmd.frame("2")
cmd.show("(25)")
cmd.mview("store")
cmd.hide('everything','all')
cmd.frame("2")
cmd.show("(26)")
cmd.mview("store")
cmd.hide('everything','all')
cmd.frame("2")
cmd.show("(27)")
cmd.mview("store")
cmd.hide('everything','all')
cmd.frame("2")
cmd.show("(28)")
cmd.mview("store")
cmd.hide('everything','all')
cmd.frame("2")
cmd.show("(29)")
cmd.mview("store")
cmd.hide('everything','all')
cmd.frame("2")
cmd.show("(30)")
cmd.mview("store")
cmd.hide('everything','all')
cmd.frame("2")
cmd.show("(31)")
cmd.mview("store")
cmd.hide('everything','all')
cmd.frame("2")
cmd.show("(32)")
cmd.mview("store")
cmd.hide('everything','all')
cmd.frame("2")
cmd.show("(33)")
cmd.mview("store")
cmd.hide('everything','all')
cmd.frame("2")
cmd.show("(34)")
cmd.mview("store")
cmd.hide('everything','all')
cmd.frame("2")
cmd.show("(35)")
cmd.mview("store")
cmd.hide('everything','all')
cmd.frame("2")
cmd.show("(36)")
cmd.mview("store")
cmd.hide('everything','all')
cmd.frame("2")
cmd.show("(37)")
cmd.mview("store")
cmd.hide('everything','all')
cmd.frame("2")
cmd.show("(38)")
cmd.mview("store")
cmd.hide('everything','all')
cmd.frame("2")
cmd.show("(39)")
cmd.mview("store")
cmd.hide('everything','all')
cmd.frame("2")
cmd.show("(40)")
cmd.mview("store")
cmd.hide('everything','all')
cmd.frame("2")
cmd.show("(41)")
cmd.mview("store")
cmd.hide('everything','all')
cmd.frame("2")
cmd.show("(42)")
cmd.mview("store")
cmd.hide('everything','all')
cmd.frame("2")
cmd.show("(43)")
cmd.mview("store")
cmd.hide('everything','all')
cmd.frame("2")
cmd.show("(44)")
cmd.mview("store")
cmd.hide('everything','all')
cmd.frame("2")
cmd.show("(45)")
cmd.mview("store")
my_view= cmd.get_view()
cmd.hide('everything','all')
cmd.frame("170")
cmd.set_view(my_view)
cmd.zoom("(all)")
cmd.mview("store")
cmd.mview("reinterpolate")
cmd.mpng("anim_pymol")
